const FIVE_MINUTES_IN_MILLISECONDS = 1000 * 60 * 5;
const MAX_NUMBER_OF_REQUESTS = 100;
const DEFAULT_OUTPUT_FILES_EXTNAME = '.png';

module.exports = {
  FIVE_MINUTES_IN_MILLISECONDS,
  MAX_NUMBER_OF_REQUESTS,
  DEFAULT_OUTPUT_FILES_EXTNAME,
};
